version: "3"

services:
  magma_node_dev:
    container_name: magma_node_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "9229:9229"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    restart: unless-stopped
  
volumes:
  node_modules:
