version: "3"

networks:
  server-dev-network:
    driver: bridge

services:
  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8080"
      - "9229:9229"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo_db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB  
    networks:
      - server-dev-network 
    restart: unless-stopped
  mongo_db:
    image: mongo:4.4.4-bionic
    container_name: mongo_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - server-dev-network
  
volumes:
  node_modules:
  dbdata:  
